### ISSUE TITLE
Software paper

### ISSUE THREAD

**Issue by realxinzhao** [marberts/piar#12]
@marberts I have completed the review.

The paper is well-written. I have only two minor suggestions for you to consider in the paper:

1. Line 27 in the Statement of Need, consider changing it to "hierarchical price indexes based on data made available by national statistical agencies". 

2. Line 43, you mentioned `piar` provides a flexible API. Do you mean the package had functions to access large scale data through APIs? Or do you simply mean a "flexible interface"?  Avoiding "API" might be better.

Thank you!

**Comment by marberts** [comment]
@realxinzhao Thanks for reviewing the paper so quickly.

For 1, stats agencies don't usually publish the data you'd need to reproduce their indexes with `piar`. I think what I had on line 27 was unclear---what I was trying to say is that `piar` can be used to make hierarchical indexes like those made by national stats agencies. To avoid confusion, and because I make this point a few times in the paper, I've simplified line 27 to 

> `piar` fills a gap in the open-source ecosystem for measuring inflation by providing a tool to build large, hierarchical price indexes.

For 2, you're right that "flexible interface" is better. I've made this change in the paper.
